modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="DioguiMs"
description='''
Adds a failsafe enchantment that prevents items from breaking when they reach their durability limit. Instead, the item will stop working until it is repaired. This mod is designed to be compatible with other mods and can be used in various modpacks.
'''
logoFile="icon.png"

[[mixins]]
config = "failsafe.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.failsafe]]
    modId = "occultism"
    type = "optional"
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"